# Define the name of the GitHub Action
name: Continuous Integration

# Define the events that will trigger the action
on:
  push:
    branches:
      - dev
      - prod

# Define environment variables
env:
  AWS_REGION: us-east-1
  DEV_ACCOUNT_ID: 267341338450
  PROD_ACCOUNT_ID: 258317103062
  ASSUME_ROLE_ARN_DEV: arn:aws:iam::267341338450:role/github-dev--sentiment
  ASSUME_ROLE_ARN_PROD: arn:aws:iam::258317103062:role/github-prod--sentiment
  LAMBDA_FUNCTION: sentiment_api

# Define permissions required for the action
permissions:
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout

# Define the jobs to be executed in the action
jobs:
  continuous-integrations:
    # Define the operating system the action will run on
    runs-on: ubuntu-latest

    # Prevent a publish loop with auto and GitHub Actions.
    if: "contains(github.event.head_commit.message, 'deploy:sentiment')"

    # Define the list of steps that the action will go through
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::818028758633:role/github_actions_role
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Configure python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api/sentiment
          python -m unittest unit_test.py 
          
      - name: Unit test python
        run: |
          cd api/sentiment
          python -m unittest unit_test.py 
          